version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lir9a0g67xtl"
s3_prefix = "sam-demo-backend"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
